server:
  port: ${SERVER_PORT:8761}


eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    prefer-ip-address: false



spring:
  application:
    name: DISCOVERY_SERVICE
