server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop_user_db?currentSchema=online_shop_users_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 7722

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  application:
    name: ACCOUNT-SERVICE


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 30


springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
